version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/src
      - /app/node_modules
    ports:
      - 5020:5020
    command: npm run start:docker
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres:14
    environment:
      POSTGRES_DB: test_api
      POSTGRES_USER: apidbuser
      POSTGRES_PASSWORD: 1ApidbusersecreT12
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
